### ISSUE TITLE
Fuselage displaced

### ISSUE THREAD

**Issue by D-ECHO** [legoboyvdlp/737-800#2]
[img]http://i.imgur.com/RmoBaZe.png[/img]
[img]http://i.imgur.com/6Ybzm0b.png[/img]
As you can see here, the fuselage is displaced a bit on the y-axis :(

**Comment by it0uchpods** [comment]
Is this fixed?

**Comment by D-ECHO** [comment]
It seems to me NO.

**Comment by it0uchpods** [comment]
It is corrected in the model file. It is centered in FGFS. I don't know why soitanen did it this way, but it works fine.
