### ISSUE TITLE
AP will not follow glide slope

### ISSUE THREAD

**Issue by CA1012** [legoboyvdlp/737-800#4]
As mentioned above the 737-8 AP will not follow the GS. I believe that the aircraft needs the newest ITAF so that it may be able to function properly.

**Comment by it0uchpods** [comment]
I'm aware of this, and it's not only the 737-800 with this problem. Some planes work fine, others don't. It is because I added a new GS controller that outputs to target-pitch-deg, instead of directly to the elevator system. The next version will have an adjustable GS controller to fix this.
